name: 物置場

description: 学生だから、お金がない。

avatar: //github.com/takusan4046.png

baseurl: ""

permalink: /:title/

paginate: 8

paginate_path: "/page:num/"

sns-button: true

sns-buttons:
  twitter: takusan_4046
  facebook:
  googleplus:
  instagram:
  hatena:
  github: takusan4046
  rss: true
  line:
  email:
  
google-custom-search:

gems:
  - jekyll-sitemap
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
